name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive 
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: "npm install"
        run: |
          npm ci
      - name: "patch deps"
        run: |
          node ./ci/patch-deps
      - name: "build jsbundle"
        run: |
          npm run bundle-rnjs
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
